export const stories = [

    //story 1 squarrel and his hurry friend.
    {
        id: 1,
        title: "The Squirrel's Secret",
        description: "A compassionate student discovers the sorrow of a grieving squirrel, leading him to unite his community in building homes for the local wildlife, transforming loss into kindness.",
        mainContent: `Once upon a time, there was an Indian-origin student pursuing his master's degree in the USA. He lived in a community with many trees. Every day, he would rush to school. A squirrel observed him daily, but the student was unaware of it.One day, as the student was on his way to school, the squirrel followed him. He was in a hurry to catch his bus and did not notice the squirrel. A couple of weeks later, on a fine weekend, he decided to take a small break from his work and step out of his room to walk around the community. After some time, he reached the pool area and decided to rest by the poolside. He grabbed a seat and watched a squirrel for about 15 minutes. The squirrel appeared sad, while the other squirrels were running and eating nuts and seeds. The student continued to watch the squirrel.After a while, the squirrel stared at him and then started running toward him. The squirrel approached with a sad expression, roaming between his legs. Its intention seemed to be to show him something, but the student didn’t understand at first. Eventually, he followed the squirrel, which led him to a little dead squirrel. The squirrel started crying, and the student picked it up and began consoling it. He took the squirrel to his room, where it made some sounds. He offered it some food, but the squirrel was not interested in eating. He decided to take the squirrel back to its place. Once he dropped it off, the squirrel ran away as fast as lightning. The student felt confused and waited there for a couple of seconds. The squirrel then returned with her babies and approached the student. At that moment, he understood the squirrel's intention. He took the babies to his room and offered them food. They ate until their tummies were full, and one baby squirrel laid on his bed. The mother squirrel started crying again, and the student felt her pain. He asked the squirrel, "What happened?" The squirrel didn’t understand his words but could sense his expressions. She didn’t know how to convey the past, but she acted like a dead squirrel for a moment before jumping toward her kids. This reminded the student of something from his past. He recalled a similar situation: a squirrel had acted the same way back then. He realized that the baby squirrel must have fallen from a tree and lost its life. If he had helped the squirrel at that time, the baby would still be alive. Tears filled his eyes. He decided to arrange a home for all the squirrels in the community. Some community members noticed him and joined in to help build homes for the squirrels. He resolved not to repeat his mistakes in the future. Every day, he visited the squirrels’ home, said hi to them, and offered water to all the squirrels. He didn’t want to offer food because...`,
        conclusion: "part 2 loading...",
        author: "karthik",
        publishedDate: "10-19-2024",

    },
    
]